### ISSUE TITLE
Sculk Config

### ISSUE THREAD

**Issue by EthanRStokes** [FrozenBlock/Configurable-Everything#14]
Sculk generation config
Possibly similar to the Customizable Sculk mod made by @AViewFromTheTop 

Contains various options regarding sculk spreading

**Comment by EthanRStokes** [comment]
@AViewFromTheTop
Would you be able to upload the source code for Customizable Sculk to a repository?
If you’d want it private you could make it a private repo and add me as a contributor.

If you don’t have it, might have to convert the decompiled sources :skull:

**Comment by AViewFromTheTop** [comment]
> @AViewFromTheTop Would you be able to upload the source code for Customizable Sculk to a repository? If you’d want it private you could make it a private repo and add me as a contributor.
> 
> If you don’t have it, might have to convert the decompiled sources 💀

Id much rather us just remake it.. the source is probably on my (now) studio PC but im at college rn lol
Anyway, remaking it as part of CE is just gonna ensure cleaner implementation and everything lmao
Both of us have improved substantially since Customizable Sculk released
