### ISSUE TITLE
Gravity Config

### ISSUE THREAD

**Issue by EthanRStokes** [FrozenBlock/Configurable-Everything#6]
Consists of elevation gravity multipliers (1.0 is default)
These
- are per dimension
- can be an instant change (`if (y >= change.value)`) or a linear slope from one point to another (I think it would be `Math.lerp(y, change.minValue, change.maxValue) * change.multiplier`)
- if overlapping, 1.0 is still default gravity

**Comment by AViewFromTheTop** [comment]
Can just take from the Moon mod
Still kinda sad that didn’t get to go anywhere

**Comment by EthanRStokes** [comment]
1/2 ish done
gravity api implemented into frozenlib
may improve the gravity api before implementing the config

**Comment by EthanRStokes** [comment]
Implemented, but it only supports absolute gravity functions (a definite gravity value for a gravity belt)
Don’t know how to interpolate gravity

**Comment by AViewFromTheTop** [comment]
> Implemented, but it only supports absolute gravity functions (a definite gravity value for a gravity belt) Don’t know how to interpolate gravity

just implement a start and end point for the gravity lol

**Comment by EthanRStokes** [comment]
For the initial gravity config this is probably okay
